### ISSUE TITLE
Restrictions to CudNN and CUDA toolkit version. 

### ISSUE THREAD

**Issue by Erik-Koning** [andersbll/cudarray#81]
I am trying to run neural_artistic_style with the Nvidia CUDA toolkit 9.1 and 7.1 cudNN. Are these newer version from nividia not supported? I have ran into many problems such as the GPU architecture not supported error in this project, and other errors in neural_artistic_style.

**Comment by Erik-Koning** [comment]
When making cudarray specifically i also recieve the error: 
src/nnet/cudnn.cpp:169:5**: error: too few arguments to function** ‘cudnnStatus_t cudnnSetConvolution2dDescriptor(cudnnConvolutionDescriptor_t, int, int, int, int, int, int, cudnnConvolutionMode_t, cudnnDataType_t)'));

**Comment by prannayk** [comment]
Yes it does seem that this library does not work with CUDA 8.0 or above

**Comment by The-Oracle** [comment]
For cudNN 7.x and CUDA 9.x compatibility, make the following change in cudnn.cpp, replace lines 167-169 with the following:

CUDNN_CHECK(cudnnSetConvolution2dDescriptor(
        conv_desc, pad_y, pad_x, stride_y, stride_x, 1, 1, CUDNN_CONVOLUTION, CUDNN_DATA_FLOAT
    ));

This will get you past the compilation error, I have not yet had the chance to test the library with cudNN 7 and CUDA 9.

**Comment by yueanga** [comment]
> 
> 
> For cudNN 7.x and CUDA 9.x compatibility, make the following change in cudnn.cpp, replace lines 167-169 with the following:
> 
> CUDNN_CHECK(cudnnSetConvolution2dDescriptor(
> conv_desc, pad_y, pad_x, stride_y, stride_x, 1, 1, CUDNN_CONVOLUTION, CUDNN_DATA_FLOAT
> ));
> 
> This will get you past the compilation error, I have not yet had the chance to test the library with cudNN 7 and CUDA 9.

it worked with cuda10 as well
thank you so much!!!!

**Comment by MobtgZhang** [comment]
I am trying to install cudarry,but the version of cuda-toolkit is cuda10.2 and cuDNN 8.2.1.32,I meet the same problems as you,how can I solve this problem?

> src/nnet/cudnn.cpp:169:5: error: too few arguments to function ‘cudnnStatus_t cudnnSetConvolution2dDescriptor(cudnnConvolutionDescriptor_t, int, int, int, int, int, int, cudnnConvolutionMode_t, cudnnDataType_t)’
     ));
     ^

**Comment by MobtgZhang** [comment]
and how about the installation of cuda10.x and cuda11.x for cudarray?

**Comment by Bernadette-Mohr** [comment]
> and how about the installation of cuda10.x and cuda11.x for cudarray?

For me, the change in the code also worked for cuda 11.6.

**Comment by SWEDEN1003** [comment]
> For cudNN 7.x and CUDA 9.x compatibility, make the following change in cudnn.cpp, replace lines 167-169 with the following:
> 
> CUDNN_CHECK(cudnnSetConvolution2dDescriptor( conv_desc, pad_y, pad_x, stride_y, stride_x, 1, 1, CUDNN_CONVOLUTION, CUDNN_DATA_FLOAT ));
> 
> This will get you past the compilation error, I have not yet had the chance to test the library with cudNN 7 and CUDA 9.

For me, it can work for cuda -11.3
